# Generated by Django 5.2.7 on 2025-11-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('date_of_birth', models.DateField(verbose_name='Data urodzenia')),
                ('gender', models.CharField(choices=[('Mężczyzna', 'Male'), ('Kobieta', 'Female'), ('Inna', 'Other')], default='Mężczyzna', max_length=9, verbose_name='Płeć')),
                ('initial_diagnosis', models.CharField(max_length=250, verbose_name='Wstępna diagnoza')),
                ('diagnosis_date', models.DateField(verbose_name='Data diagnozy')),
            ],
        ),
    ]
