# Generated by Django 5.2.7 on 2025-11-06 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('protocol_name', models.CharField(choices=[('Chemoterapia', 'Chemo'), ('Terapia hormonalna', 'Hormon'), ('Immunoterapia', 'Immuno'), ('Terapia fotodynamiczna', 'Photo'), ('Terapia celowana', 'Target')], max_length=200, verbose_name='Rodzaj terapii')),
                ('status', models.CharField(choices=[('W trakcie', 'Ongoing'), ('Zakończona', 'Completed'), ('Wstrzymana', 'Paused'), ('Zaplanowana', 'Planned')], max_length=200, verbose_name='Status terapii')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_cycles', to='patient.patient', verbose_name='Pacjent')),
            ],
        ),
    ]
