# Generated by Django 5.2.7 on 2025-12-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_therapycycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(verbose_name='Data oceny reakcji')),
                ('recist_result', models.CharField(choices=[('CR', 'CR - complete response'), ('PR', 'PR - partial response'), ('SD', 'SD - stable disease'), ('PD', 'PD - progressive disease')], default='SD', max_length=2, verbose_name='Kryterium RECIST')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Notatki')),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='patient.therapycycle', verbose_name='Terapia')),
            ],
        ),
    ]
