# Generated by Django 5.2.7 on 2025-12-09 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_response_recist_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='cycle_id',
        ),
        migrations.AddField(
            model_name='response',
            name='response_cycle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_ci', to='patient.therapycycle', verbose_name='Terapia'),
        ),
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Data zdarzenia')),
                ('description', models.TextField(max_length=1500, verbose_name='Opis zdarzenia')),
                ('severity', models.CharField(choices=[('Grade 1', 'G1'), ('Grade 2', 'G2'), ('Grade 3', 'G3'), ('Grade 4', 'G4'), ('Grade 5', 'G5')], default='Grade 1', verbose_name='Severity')),
                ('action_taken', models.TextField(max_length=1500, verbose_name='Podjęte działanie')),
                ('adverse_event_cycle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_response', to='patient.therapycycle', verbose_name='Terapia')),
            ],
        ),
    ]
