# Generated by Django 5.2.7 on 2025-12-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_response_cycle_id_response_response_cycle_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(help_text='The 15-character ENSEMBL stable ID (e.g., ENSG00000139618)', max_length=15, verbose_name='ENSEMBL Gene ID')),
                ('mutation_type', models.CharField(choices=[('MISSENSE', 'Missense'), ('NONSENSE', 'Nonsense'), ('FRAMESHIFT', 'Frameshift'), ('SILENT', 'Silent'), ('SPLICE_SITE', 'Splice Site'), ('INDEL', 'Indel'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('vaf', models.FloatField(verbose_name='VAF')),
                ('mutation_patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_mutations', to='patient.patient', verbose_name='ID_Pacjenta')),
            ],
        ),
    ]
