# Generated by Django 5.2.7 on 2025-12-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_mutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapycycle',
            name='protocol_name',
            field=models.CharField(choices=[('Chemoterapia', 'Chemo'), ('Terapia hormonalna', 'Hormon'), ('Immunoterapia', 'Immuno'), ('Terapia fotodynamiczna', 'Photo'), ('Terapia celowana', 'Target'), ('Radioterapia', 'Radio')], max_length=200, verbose_name='Rodzaj terapii'),
        ),
    ]
