# Generated by Django 5.2.7 on 2026-01-24 09:38

import django.core.validators
import django.db.models.deletion
import patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_therapycycle_protocol_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('pwz_number', models.CharField(help_text='7-cyfrowy numepr prawa wykonywania zawodu', max_length=7, unique=True, verbose_name='Numer PWZ')),
                ('specialization', models.CharField(choices=[('ONKOLOG', 'Onkolog kliniczny'), ('ONKOGENETYK', 'Onkogenetyk'), ('RADIOLOG', 'Radiolog'), ('PATOMORFOLOG', 'Patomorfolog'), ('CHIRURG', 'Chirurg onkologiczny'), ('INNY', 'Inna specjalizacja')], default='ONKOLOG', max_length=50, verbose_name='Specializacja')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email służbowy')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon kontaktowy')),
            ],
            options={
                'verbose_name': 'Lekarz',
                'verbose_name_plural': 'Lekarze',
            },
        ),
        migrations.AlterModelOptions(
            name='adverseevent',
            options={'verbose_name': 'Zdarzenie niepożądane', 'verbose_name_plural': 'Zdarzenia niepożądane'},
        ),
        migrations.AlterModelOptions(
            name='mutation',
            options={'verbose_name': 'Mutacja', 'verbose_name_plural': 'Mutacje'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Pacjent', 'verbose_name_plural': 'Pacjenci'},
        ),
        migrations.AlterModelOptions(
            name='therapycycle',
            options={'verbose_name': 'Cykl Terapii', 'verbose_name_plural': 'Cykle Terapii'},
        ),
        migrations.RemoveField(
            model_name='adverseevent',
            name='adverse_event_cycle_id',
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='therapy_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', to='patient.therapycycle', verbose_name='Cykl terapii'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Miejscowość'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ulica i nr domu'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_zip_code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{3}$', 'Format kodu: XX-XXX')], verbose_name='Kod pocztowy'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pesel',
            field=models.CharField(blank=True, help_text='11-cyfrowy numer identyfikacyjny', max_length=11, null=True, unique=True, validators=[patient.models.validate_pesel], verbose_name='PESEL'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='severity',
            field=models.CharField(choices=[('Grade 1', 'Grade 1 - Łagodne'), ('Grade 2', 'Grade 2 - Umiarkowane'), ('Grade 3', 'Grade 3 - Ciężkie'), ('Grade 4', 'Grade 4 - Zagrażające życiu'), ('Grade 5', 'Grade 5 - Zgon')], default='Grade 1', verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mutation_patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='patient.patient', verbose_name='Pacjent'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mutation_type',
            field=models.CharField(choices=[('MISSENSE', 'Missense'), ('NONSENSE', 'Nonsense'), ('FRAMESHIFT', 'Frameshift'), ('SILENT', 'Silent'), ('SPLICE_SITE', 'Splice site'), ('INDEL', 'Indel'), ('OTHER', 'Inna')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data diagnozy (ARCHIWALNE)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Mężczyzna', 'Mężczyzna'), ('Kobieta', 'Kobieta'), ('Inna', 'Inna')], default='Mężczyzna', max_length=15, verbose_name='Płeć'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='initial_diagnosis',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Wstępna diagnoza (ARCHIWALNE)'),
        ),
        migrations.AlterField(
            model_name='therapycycle',
            name='protocol_name',
            field=models.CharField(choices=[('Chemoterapia', 'Chemioterapia'), ('Terapia hormonalna', 'Terapia hormonalna'), ('Immunoterapia', 'Immunoterapia'), ('Terapia fotodynamiczna', 'Terapia fotodynamiczna'), ('Terapia celowana', 'Terapia celowana'), ('Radioterapia', 'Radioterapia')], max_length=200, verbose_name='Rodzaj terapii'),
        ),
        migrations.AlterField(
            model_name='therapycycle',
            name='status',
            field=models.CharField(choices=[('W trakcie', 'W trakcie'), ('Zakończona', 'Zakończona'), ('Wstrzymana', 'Wstrzymana'), ('Zaplanowana', 'Zaplanowana')], max_length=200, verbose_name='Status terapii'),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_code', models.CharField(blank=True, help_text='np. C34.1', max_length=10, null=True, verbose_name='Kod ICD-10')),
                ('name', models.CharField(max_length=250, verbose_name='Rozpoznanie opisowe (np. Rak płuca)')),
                ('diagnosis_date', models.DateField(verbose_name='Data postawienia diagnozy')),
                ('tumor_stage', models.CharField(blank=True, help_text='Wielkość guza pierwotnego (np. T1, T2)', max_length=10, null=True, verbose_name='Cecha T (Guz)')),
                ('node_stage', models.CharField(blank=True, help_text='Stan regionalnych węzłów chłonnych (np. N0, N1)', max_length=10, null=True, verbose_name='Cecha N (Węzły)')),
                ('metastasis_stage', models.CharField(blank=True, help_text='Obecność przerzutów odległych (np. M0, M1)', max_length=10, null=True, verbose_name='Cecha M (Przerzuty)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis szczegółowy / Wynik hist-pat')),
                ('status', models.CharField(choices=[('PODEJRZENIE', 'Podejrzenie'), ('POTWIERDZONA', 'Potwierdzona histopatologicznie'), ('WZNOWA', 'Wznowa'), ('REMISJA', 'Remisja (Wyleczona)'), ('PALIATYWNA', 'Opieka paliatywna')], default='POTWIERDZONA', max_length=20, verbose_name='Status diagnozy')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patient.patient', verbose_name='Pacjenci')),
            ],
            options={
                'verbose_name': 'Diagnoza',
                'verbose_name_plural': 'Historia Chorób (Diagnozy)',
                'ordering': ['-diagnosis_date'],
            },
        ),
        migrations.AddField(
            model_name='therapycycle',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapy_cycles', to='patient.diagnosis', verbose_name='Leczona choroba'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Data i godzina wizyty')),
                ('appointment_type', models.CharField(choices=[('KONSULTACJA', 'Konsultacja lekarska'), ('KONTROLA', 'Badanie kontrolne'), ('ZABIEG', 'Drobny zabieg'), ('KWALIFIKACJA', 'Kwalifikacja do leczenia')], default='KONSULTACJA', max_length=50, verbose_name='Rodzaj wizyty')),
                ('status', models.CharField(choices=[('ZAPLANOWANA', 'Zaplanowana'), ('ODBYTA', 'Odbyta'), ('ANULOWANA', 'Anulowana'), ('NIESTAWIENNICTWO', 'Pacjent nie przyszedł')], default='ZAPLANOWANA', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notatki z wizyty')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patient.patient', verbose_name='Pacjent')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patient.doctor', verbose_name='Pacjent')),
            ],
            options={
                'verbose_name': 'Wizyta',
                'verbose_name_plural': 'Wizyty',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='attending_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_patients', to='patient.doctor', verbose_name='Lekarz Prowadzący'),
        ),
        migrations.AddField(
            model_name='patient',
            name='consulting_doctors',
            field=models.ManyToManyField(blank=True, related_name='consultation_patients', to='patient.doctor', verbose_name='Lekarze konsultujący'),
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nazwa dokumentu (np. Wynik TK)')),
                ('file', models.FileField(blank=True, null=True, upload_to='medical_documents/')),
                ('upload_date', models.DateField(blank=True, null=True, verbose_name='Data dodania dokumentu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Komentarz')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='patient.patient', verbose_name='Pacjent')),
            ],
            options={
                'verbose_name': 'Dokument medyczny',
                'verbose_name_plural': 'Dokumentacja medyczna',
                'ordering': ['-upload_date'],
            },
        ),
    ]
