# Generated by Django 5.2.7 on 2026-01-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_doctor_alter_adverseevent_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutation',
            old_name='mutation_patient_id',
            new_name='patient',
        ),
    ]
